### ISSUE TITLE
create MappedPasswordHash field to replace MappedPassword

### ISSUE THREAD

**Issue by toddobryan** [lift/framework#1020]
http://groups.google.com/group/liftweb/browse_thread/thread/cbe05606847e922/

MappedPassword fails silently when you set it programmatically in a way that is inconsistent with validation. It's also more complicated than it needs to be.

The discussion above lists a couple of other desiderata.

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
