### ISSUE TITLE
squeryl-record doesn't honor StringFields as objects

### ISSUE THREAD

**Issue by indrajitr** [lift/framework#1134]
squeryl-record doesn't work with StringFields created as so:

object f extends StringField(this, 36)

instead requiring:

val f = new StringField(this, 36)

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
