### ISSUE TITLE
User with MetaMegaProtoUser and CRUDify do not compile

### ISSUE THREAD

**Issue by indrajitr** [lift/framework#1172]
In Lift version 2.9.0 when using MetaMegaProtoUser and Crudify  together in an user object it doesn't compile.

There are conflicts with same def/val names used by both Traits.

_User definition:_

```
...
line 136:  object User extends User with MetaMegaProtoUser[User] with CRUDify[Long, User] {_ 
...
```

_Error:_

```
.../model/User.scala:136: overriding type FieldPointerType in trait MetaMegaProtoUser, which equals net.liftweb.mapper.MappedField[_, ingo.model.User.TheUserType];
[error]  type FieldPointerType in trait CRUDify, which equals net.liftweb.mapper.MappedField[_, ingo.model.User] needs `override' modifier;
[error]  other members with override errors are: computeFieldFromPointer, buildFieldBridge, editPath, menus
[error] object User extends User with MetaMegaProtoUser[User] with CRUDify[Long, User]{
[error]        ^
[error] one error found
```

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
