### ISSUE TITLE
Left join problem on none numeric data type for SquerylRecord

### ISSUE THREAD

**Issue by lunaspeed** [lift/framework#1174]
When doing left join on none numeric data type there will be type miss match error

class Fund private() extends Record[Fund] with KeyedRecord[String] { 
    ...
    val id = new StringField(this, 8) 
    val lcc = new OptionalStringField(this, 8) 
  } 

  class Lc private() extends Record[Lc] with KeyedRecord[String] { 
    ...
    val lcc = new StringField(this, 8) 
    val name = new StringField(this, 8) 
  } 

  val d = join(fund, lc.leftOuter)((f, l) => 
    where(f.id === "xxx") 
    select(f, l) 
    on(f.lcc === l.map(_.lcc))) 

Error mismatch on last line  "on(f.lcc === l.map(_.lcc))"
Due to f.lcc is converted to some sort of  StringExpression[String] instead of StringExpression[Option[String]]

current work arrount is "on(Some(f.lcc) === l.map(_.lcc))"

more discussion in
[[url:https://groups.google.com/group/liftweb/browse_thread/thread/eb88859a2ca51f9b/e9b97b357c06be1c|ExampleName]]

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
