### ISSUE TITLE
Use explicit return types in RecordTypeMode implicits

### ISSUE THREAD

**Issue by rusho** [lift/framework#1175]
Implicits in RecordTypeMode don't have explicit return types. We should be explicit about return types in implicits, otherwise less than optimal things happen in the compiler

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
