### ISSUE TITLE
MappedText - check that value is dirty in real_i_set_! method

### ISSUE THREAD

**Issue by amullins** [lift/framework#1189]
The real_i_set_! method of MappedText does not check that the value is dirty before assigning it to data.
[[url:https://groups.google.com/d/topic/liftweb/i2v9eqOQ6eg/discussion|Mailing List Thread]]

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
