### ISSUE TITLE
mapper DB.runUpdate crashes if question marks in valid strings

### ISSUE THREAD

**Issue by TimPigden** [lift/framework#1248]
the following will fail

DB.runUpdate("insert into myTable (name, comment) values ('Tim', 'Why?'), Nil)

because the code in mapper is incorrectly parsing for ? as a parameter in the entire sql statement not just in parameter positions.

See this post for discussion

https://groups.google.com/forum/?hl=en&fromgroups#!topic/liftweb/2wxkFMK-niY

including trace and source code reference

Suggested short-term workaround:
create DB.runUpdate(sql: String)  with no parameters

and return error instead of crashing and looking for items in empty param list

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
