### ISSUE TITLE
UUID field support in squeryl-record

### ISSUE THREAD

**Issue by lamielle** [lift/framework#1313]
In squeryl-record, there should be support for UUID fields including autogenerating primary keys (KeyedRecord[UUID]).  Squeryl has support for native UUID columns, so this issue is to plumb through support for this in squeryl-record and possibly Record itself.

**Comment by askalski** [comment]
Hello,
I would use UUID Field in Squeryl-record as well. Are there any news on it's progress?

Maybe I could write one myself? Where to start?

Andrzej

**Comment by fmpwizard** [comment]
you can bring this up to the mailing list and there people will be able to better help you write your own and/or give you more info on this.

Thanks

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
