### ISSUE TITLE
Reload all or a specific template in production without app restart.

### ISSUE THREAD

**Issue by oolekk** [lift/framework#1315]
In production mode, one has to restart the whole app to reload templates, which seems to be an overkill for minor adjustments. Here is a link to the topic at mailinglist: https://groups.google.com/forum/?fromgroups=#!topic/liftweb/oqFNzoA_vs4

**Comment by Shadowfiend** [comment]
In fact, I think this should just be a matter of changing the [template cache defaulting in production mode in `HTTPProvider`](https://github.com/lift/framework/blob/5033c8798d4444f81996199c10ea330770e47fbc/web/webkit/src/main/scala/net/liftweb/http/provider/HTTPProvider.scala#L121-L124) to happen pre-boot instead of post-boot. We'd need to confirm that pre-boot gives `LiftRules` a chance to initialize to its default `Empty` before we check it and set it to `Full` by default in production mode.

Another option would be to move that defaulting directly into the [`LiftRules` initialization of `templateCache`](https://github.com/lift/framework/blob/5033c8798d4444f81996199c10ea330770e47fbc/web/webkit/src/main/scala/net/liftweb/http/LiftRules.scala#L1881), as we do similar mode-based toggling in several places in `LiftRules`.

Even without this, `LiftRules.templateCache` can be set to a subclass of `InMemoryCache` that allows for further customization, and the above defaulting of the cache won't take place in that case. (Even as it stands, the default cache allows for deletions to occur.)
