### ISSUE TITLE
Add Squeryl transaction LoanWrapper

### ISSUE THREAD

**Issue by davewhittaker** [lift/framework#1437]
It was [pointed out](https://groups.google.com/d/msg/liftweb/2df8_E47YKU/qGFaXoMmH_AJ) that the LoanWrapper implementation on the Wiki doesn't handle Lift's control flow exceptions properly and will roll back a transaction on S.redirectTo.  We'll need to get a custom LoanWrapper implemented that handles these properly.

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
