### ISSUE TITLE
Minimalized common AST for JSON (json4s-ast)

### ISSUE THREAD

**Issue by mdedetrich** [lift/framework#1715]
Some time ago, major web frameworks such as lift/spray, as well as typesafe were interested in adopting a minimalized AST of json4s, in an attempt to establish a common json AST to be used by scala libraries.

At JSON4s we have recently begun reviving this effort. So far we have received input/contributions from  current major players (https://github.com/non/jawn, http://spray.io/, https://github.com/lift/framework, https://github.com/propensive/rapture-json, https://github.com/json4s/json4s, http://www.scala-sbt.org/ as well as others)

If you are interested, we would be glad to have your input either at gitter (json4s/json4s) or you can comment directly on the pull request (https://github.com/mdedetrich/json4s-ast/tree/reboot) and issues (https://github.com/json4s/json4s-ast/issues).

**Comment by farmdawgnation** [comment]
Hey this sounds awesome. Can you throw it on the liftweb mailing list? Our policy as a community is to have these sort of discussions there so everyone - more than just those of us who happen to watch the project - can participate too. Otherwise conversations risk excluding users of the framework. :/

I'll probably try to take a look at your work soonish.

**Comment by farmdawgnation** [comment]
I'll actually go ahead and forward this into the ML for you and close this issue.

Cheers!

**Comment by mdedetrich** [comment]
Cool, will put it on the mailing list
