### ISSUE TITLE
Add 'X-Requested-With' header to liftVanilla

### ISSUE THREAD

**Issue by eltimn** [lift/framework#1745]
Lift checks for that header in `Req.ajax_?` to determine if the request is ajax.

**Comment by farmdawgnation** [comment]
Can we just make it `Requested-With`? The `X-` prefix is deprecated, I'm told.

**Comment by eltimn** [comment]
I did not know that.

I don't see why we can't do that. I'll have to update `Req.ajax_?` as well to recognize both as jQuery still uses the 'X' version.

**Comment by Shadowfiend** [comment]
Er… Hang on. Source for the deprecation on this particular header? `X-` is deprecated for new headers, but [the RFC that deprecated it](http://tools.ietf.org/html/rfc6648) ‘[m]akes no recommendation as to whether existing "X-" parameters ought to remain in use or be migrated to a format without the "X-"; this is a matter for the creators or maintainers of those parameters.’ Given that we are in no way shape or form maintainers of the parameter and [the latest jQuery](https://github.com/jquery/jquery/blob/769446c69775f6c44e35cee1bcdeccafba51be7b/src/ajax/xhr.js#L57-L64) still uses `X-Requested-With`, I don't think we should be changing our usage.

**Comment by farmdawgnation** [comment]
Oh, I didn't realize we were doing this to connect in to some jQuery functionality.

**Comment by farmdawgnation** [comment]
Heh. Re-reading the ticket it's obvious I didn't read it that closely to start with. Move along... nothing to see here.

**Comment by Shadowfiend** [comment]
Fwiw, it's not per se jQuery functionality—`X-Requested-With` is at this point a de facto standard due to early use by mochiweb, jQuery, prototype, and mootools if I remember correctly. My point was more that since jQuery was one of the early adopters of it and continues to use it this way (probably to not break any older stuff), we should be wary of changing what we're doing unless we have some strong sources on community decisions to change the header.
