### ISSUE TITLE
Set default cookie path for MetaProtoExtendedSession to contextPath

### ISSUE THREAD

**Issue by Debilski** [lift/framework#1758]
As suggested in https://groups.google.com/d/msg/liftweb/ZWmPdpIG1JA/dfAzbXiTBgAJ the cookie path for `MetaProtoExtendedSession` should be configurable and/or default to contextPath.

**Comment by Shadowfiend** [comment]
This should be as simple as updating https://github.com/lift/framework/blob/master/persistence/mapper/src/main/scala/net/liftweb/mapper/ProtoExtendedSession.scala#L95 to use `S.contextPath` instead of `"/"`, I think. However, this would be a breaking change.

As such, we probably need to make this customizable instead. I think we can add a:

```scala
  def sessionCookiePath: String = "/"
```

To the `trait`. We can even add a new trait, `ContextPathExtendedCookie`, that sets the above to `S.contextPath`, so you could do `extends MetaProtoExtendedSession with ContextPathExtendedCookie` or something like that.
