### ISSUE TITLE
Streaming JSON parser

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1795]
@Shadowfiend sold me on the idea of a streaming parser for lift-json. So something like...

``` scala
// Open yr input stream
val inputStream = ...
// Some arbitrary thing to track your state
case class StreamingState(...)
val initialState = StreamingState(...)

parseFromStream[StreamingState](inputStream, initialState) {
  case JParserEvent(JField(name, value), hierarchy, currentState) if name == "foo" =>
    // do something with the field you found, return updated state
    ContinueParsing(currentState.copy(...))

  case JParserEvent(JField(name, _), _, currentState) if name == "bar" =>
    // abort parsing because we're done!
    AbortParsing(currentState.copy(...))
}
```

A very loose sketch... but would enable the possibility of parsing streams of `JObject` without pulling the entire thing into memory.

**Comment by andreak** [comment]
+1, definitely useful!

**Comment by Shadowfiend** [comment]
I could have sworn I'd seen support for this in lift-json, and it turns out I 100% have because lift-json already supports this parsing model:

```scala
val result =
  JsonParser.parse("""{"someJson": "hai", "moreJson": "bai", "extraJson": 2.0}""", { parser: Parser =>
    var token = parser.nextToken
    while (token != End) {
      token match {
        case OpenObj => ...
        case FieldStart(fieldName) => ...
        ...
      }

      token = parser.nextToken
    }
  })
```

Not only does lift-json support it… [The non-pull parser is built on the pull parser](https://github.com/lift/framework/blob/master/core/json/src/main/scala/net/liftweb/json/JsonParser.scala#L187-L202)!

I think we can put a prettier API on top of it, but this is 100% already handled by lift-json out of the box which is pretty neat-o-rific.

**Comment by farmdawgnation** [comment]
Given that this API already exists (and how long I've _already_ let this languish) I'm going to close this issue. If this API gets used and we get concrete suggestions for better APIs those make sense as separate tickets. As it stands, this ticket is no longer actionable so it languishes. :)

**Comment by Shadowfiend** [comment]
I think there's still value to a prettified interface that looks a little more functional; that is, that takes a function with state + current token that returns an updated state, and handles e.g. token ends and such; however, I remember looking at this and it will be a decent chunk of work, since we'd basically be sticking an intermediary between the pull parser and the passed function that takes care of e.g. bundling up fields, objects, etc. The pull parser works strictly on very low-level events (e.g. `OpenObj`, `FieldStart`), while a cleaner API would *probably* work in terms of more familiar lift-json objects (e.g. `JValue` subclasses).

Anyway, yeah. For another time.
