### ISSUE TITLE
Deploying to AWS is nearly impossible

### ISSUE THREAD

**Issue by alexflav23** [lift/framework#1833]
Trying to get Lift working on Elastic Beanstalk is a privilege reserved for the finest among our craft, because it is an exercise in pain tolerance thresholds.

I know you want a mailing list discussion to go with this, but I'd rather join the rest of the world that uses GitHub issues as opposed to a highly arcane mailing list that doesn't even do proper code highlighting don't you think? I think my time as well as others is valuable, so why go through 50 channels to discuss the same issue, this is insane.

Ever since 3.0, Lift has become extremely unstable to handle, and randomly breaks because CSP doesn't evaluate properly. Setup is also arbitrarily ignored, even if production settings are forced in dev mode for validation, there are things in Lift that probably silently fail or at the very least bubble up as a failure to parse the CSP report, it's an extremely flaky feature for whatever reason, meaning sometimes everything starts up normally, sometimes it blows up with a CSP report exception, even though nothing changes?

I can only assume it's a variant of the same problem outlined below, which is that there's an error so early in the init pipeline the endpoint that should return the CSP doesn't come back with anything and therefore none of the content sources on a page are valid.

Replicating:

- Elastic Beanstalk
- 64bit Amazon Linux 2016.09 v2.5.3
- Running Tomcat 8 Java 8

The first welcoming error:

```scala
org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_init]) for component [Connector[HTTP/1.1-8080]] in state [INITIALIZED]
	at org.apache.catalina.util.LifecycleBase.invalidTransition(LifecycleBase.java:402)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:343)
	at webapp.runner.launch.Main.main(Main.java:275)
```

Behaviour:

- Lift inconsistently works or fails depending on weather conditions
- Updating or re-deploying Lift seems to trigger some extremely vulnerable CSP related internals that just blow up when the world is dearest.
- This has been happening for quite a while, across many Lift framework versions.

I think there should be some kind of strong compatibility notice with Lift, explicitly saying the framework no longer works or is compatible with latest AWS ElasticBeanstalk/Tomcat deployments, because it is absolutely impossible to work with.

In our case, we are slowly moving all our applications away from Lift and to more mature and well maintained alternatives. There are daemons and dragons in Lift that currently make it impossible to work with on AWS/Tomcat and since there's no servlet-less flavour, every increment of new releases has made our lives ever more painful.

It's along this part of the log everything consistently goes south, through very unpredictably. Sometimes when doing rolling updates, sometimes when restarting etc. 

```
16:41:05.918 [localhost-startStop-2] DEBUG net.liftweb.http.LiftServlet - Destroyed Lift handler.
12-Apr-2017 16:41:06.105 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [threadDeathWatcher-2-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
```

**Comment by farmdawgnation** [comment]
Flavian,

I want to start off by making a few remarks about the tone of your post. First, let me make clear that I am sympathetic to the fact that you're obviously having a frustrating day. It is probably the single most unifying experience in our trade. **That said** this post was rude. We have no tolerance for folks coming in and being generally rude to us when we've volunteered our time and effort.

Now, to your specific issue. Judging by the mailing list history, you've only participated in five threads. In at least one thread you were [asked to provide a sample project](https://groups.google.com/d/msg/liftweb/5BwZNQBDEw4/_ho_LF_6CQAJ) since none of us have a ton of experience with Tomcat. In another, [you were asked to fill out an issue](https://groups.google.com/d/msg/liftweb/P6OqQnfocwE/GWesuUvaCAAJ) and it seems as though you did not. In several others people have tried to work with you to find solutions to your problems, but the thread just kind of drops off?

Net-net: It looks a lot like you're not really willing to do the work to make sure your issues get addressed and would instead to prefer to just complain. This issue fits that narrative pretty well because you opened an issue that:

* Intentionally (and knowingly) disregards our process for dealing with issues.
* Provides very little useful detail, or a sample project, that lets us reproduce the error.
* Is not written in the spirit of actually working towards a solution to this issue.

If you'd like to come to the list and discuss this further, we'd be happy to work with you toward a workable solution if you're willing to _help_ us help you. If not, however, that is your decision.
