### ISSUE TITLE
Add Constraints To Mapper

### ISSUE THREAD

**Issue by indrajitr** [lift/framework#476]
from the mailing-list
"You could have a a Constraint trait, which has some method to get the
relevant SQL, as well as an optional function to define the constraint
name.
There would be classes that implement that-Eg: UniqueConstraint,
CheckConstraint, (to be able to do something like CHECK (column > 0)),
NotNullConstraint, PrimaryKeyConstraint, ForeignKeyConstraint (the
last two are already implemented in Mapper in a different Mapper)

Then each Mapped field would have a List[Constraint] of constraints.
In the Schemifier, ensureConstraints would then iterate over each
field (as it does now) and then construct the ALTER TABLE syntax.
The user would of course be able to define their own Application/
Database-specific constraints easily as well. "

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
