### ISSUE TITLE
Mapper, enhanced functionality: Inform user about conversion failure

### ISSUE THREAD

**Issue by MrMistr** [lift/framework#643]
When a form is submitted and for example a date field contains letters, the conversion in the respective field fails silently.
Currently there is no built-in way to inform the user of that event. 
The normal validation occurs after the (un)successful conversion.

A "work-around" trait was suggested [[url:http://groups.google.com/group/liftweb/browse_thread/thread/1b8b50be264b5848#|here]] as well as the desire for an feature enhancement ticket.

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
