### ISSUE TITLE
Option to return aliased column names from Mapper Raw SQL methods.

### ISSUE THREAD

**Issue by MattARobinson** [lift/framework#687]
Currently, the methods DB.performQuery and DB.runQuery return a (List[String], List[List[Any]]) with the first item in the tuple being a List of column names.
When running a query with aliased column names, e.g. 

<pre><code>SELECT FirstName AS GivenName FROM accounts WHERE id = 1
</code></pre>

 The underlying field name (FirstName) is returned rather than the aliased name (GivenName).

It would be very useful to have the option of getting the aliased names instead - but obviously keep the existing behaviour as the default to maintain backwards compatibility.  This is especially needed when joining two tables that have a column with the same name.

I believe that the code which does this currently is in the DB.resultSetTo and DB.resultSetToAny methods.  Currently, the line which gets the column names reads:

<pre><code>val colNames = cntList.map(i => md.getColumnName(i))
</code></pre>

A supplemental version to get the aliased names as an alternative should instead read:

<pre><code>val colNames = cntList.map(i => md.getColumnLabel(i))
</code></pre>

This enhancement has been discussed on the mailing list in these threads:

[[url:http://groups.google.com/group/liftweb/browse_thread/thread/1b82ab568d10328c/c43c585f80be38f5|should use getColumnLabel insead of getColumnName in DB.resultSetToXXX ]]
[[url:http://groups.google.com/group/liftweb/browse_thread/thread/bd699357831dafcd/7a85b4312662ca51#7a85b4312662ca51|Mapper - Column Labels vs Column Names]]

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
