### ISSUE TITLE
Add support for using ROW_NUMBER with Oracle to achieve LIMIT/OFFSET

### ISSUE THREAD

**Issue by dchenbecker** [lift/framework#692]
See this thread for discussion:

http://groups.google.com/group/liftweb/browse_thread/thread/4e2df84fb14275f2

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
