### ISSUE TITLE
ByList with IN instead of concatenated ORs

### ISSUE THREAD

**Issue by jbackes** [lift/framework#758]
Current discussion:
http://groups.google.com/group/liftweb/browse_thread/thread/c6e03492e59c0b0b

Old discussions:
http://groups.google.com/group/liftweb/browse_thread/thread/1cf5c0e153e98b47/5b60451a961ad78d
http://groups.google.com/group/liftweb/browse_thread/thread/9d68ee4182f82ef/9d3d5ffd04e3a9b3

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
