### ISSUE TITLE
Optionally Terminate ProtoUser sessions on IP change

### ISSUE THREAD

**Issue by dpp** [lift/framework#781]
Support for terminating ProtoUser sessions on IP address change

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
