### ISSUE TITLE
drop setFromAny from record API

### ISSUE THREAD

**Issue by harryh** [lift/framework#887]
It's a pretty bad/annoying API that was developed a looooong time ago and has outlived it's usefulness.  Will require a deprecation cycle.

Possibly should be dropped from Mapper API as well (though I personally care less about that).

**Comment by Shadowfiend** [comment]
Removing the milestone on this since we still have no clear deprecation plan.

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
