### ISSUE TITLE
Referential actions for foreign keys in Mapper

### ISSUE THREAD

**Issue by rusho** [lift/framework#934]
It'd be nice, if one could define referential actions for Mapper's foreign key, so that Schemifier will create such FKs and one wouldn't have to redefine FKs manually afterwards. By referential actions I mean what should be done if referenced row in parent table is updated or deleted (CASCADE, NO ACTION, RESTRICT, SET NULL, SET DEFAULT). Currently all FKs are defined as "ON UPDATE NO ACTION ON DELETE NO ACTION".

GoogleGroups thread: http://groups.google.com/group/liftweb/browse_thread/thread/67e00c37772dea91#

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
